# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Dot product in Rcpp.
#'
#' @param x1 numeric vector
#' @param x2 numeric vector
#' @return dot product, that is \code{t(x1)%*%x2}
#' @export
dotRcpp <- function(x1, x2) {
    .Call(`_geneclade_dotRcpp_I`, x1, x2)
}

#' @export
do_simulation <- function(map_elevation_vector, map_k_vector, map_temperature_vector, extirpation_depen_temperature, colonization_depen_temperature, x_max, y_max, all_x, all_y, all_IDs, all_parents, all_births, all_deaths, all_traits, all_ranges, all_alleles, all_alleles_neutral, all_popsize, number_spp, the_seed, mutation_rate, percentage_flow, geneflow_rate, popchange_rate, the_gammas, the_mus, t_change_rates, ice_age_change, q, lambda, sd_normal_distribution, starting_time, simulated_time, maximum_cycles, use_k, restiction_par, show_richness_map, v, alleles_adaptation_coef2, global_reducing, vicariant_speciation) {
    .Call(`_geneclade_do_simulation`, map_elevation_vector, map_k_vector, map_temperature_vector, extirpation_depen_temperature, colonization_depen_temperature, x_max, y_max, all_x, all_y, all_IDs, all_parents, all_births, all_deaths, all_traits, all_ranges, all_alleles, all_alleles_neutral, all_popsize, number_spp, the_seed, mutation_rate, percentage_flow, geneflow_rate, popchange_rate, the_gammas, the_mus, t_change_rates, ice_age_change, q, lambda, sd_normal_distribution, starting_time, simulated_time, maximum_cycles, use_k, restiction_par, show_richness_map, v, alleles_adaptation_coef2, global_reducing, vicariant_speciation)
}

#' @export
try_random_wallenius <- function(number_alelles, mlist_vector, wlist_vector, items_to_take) {
    .Call(`_geneclade_try_random_wallenius`, number_alelles, mlist_vector, wlist_vector, items_to_take)
}

